# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: SJTU CSC Lab  # Website name
baseURL: 'http://www.csc-lab.com/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: true
defaultContentLanguageInSubdir: fasle
# 移除URL路径中的重音符号（例如：将 "café" 转换为 "cafe"）
removePathAccents: true

# 多语言相关设置
enableMissingTranslationPlaceholders: true # 英文内容直接在根路径下，不需要翻译
enableInlineShortcodes: true

# 语言切换器配置
params:
  languages:
    - code: en
      name: English
      flag: us
    - code: zh
      name: 中文
      flag: cn

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: 'author/:slug/'
  tags: 'tag/:slug/'
  categories: 'category/:slug/'
  publication_types: 'publication-type/:slug/'
  # post: 'post/:slug/'
  # project: 'project/'
  # people: 'people/'
  # contact: 'contact/'
  # tour: 'tour/'
  # publication: 'publication/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms
      disable: false
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5

# 添加内容类型配置
# contentTypes:
#   home:
#     basedir: content
#     path: "{{.Lang}}"
#     title: "{{ .Title }}"
#     type: landing
#   people:
#     basedir: content
#     path: "{{.Lang}}/people"
#     type: landing
#   contact:
#     basedir: content
#     path: "{{.Lang}}/contact"
#     title: "{{ .Title }}"
#     type: landing
#   project:
#     basedir: content
#     path: "{{.Lang}}/project"
#     title: "{{ .Title }}"
#     type: landing
#   post:
#     basedir: content
#     path: "{{.Lang}}/post"
#     title: "{{ .Title }}"
#     type: landing
#   tour:
#     basedir: content
#     path: "{{.Lang}}/tour"
#     title: "{{ .Title }}"
#     type: landing
#   publication:
#     basedir: content
#     path: "{{.Lang}}/publication"
#     title: "{{ .Title }}"
#     type: landing
