# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  title: Complicated System and Control
  weight: 1

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-cn
  languageName: 简体中文
  contentDir: content/zh
  title: 复杂系统与控制
  weight: 2
