# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  title: SJTU CSC Lab
  weight: 1
  params:
    description: A premier research facility dedicated to advancing the field of model predictive control.
    address_format: en-us
    footer:
      copyright:
        notice: '© {year} SJTU CSC Lab. All Rights Reserved.'

zh:
  languageCode: zh-cn
  languageName: 中文
  contentDir: content/zh
  title: 上海交大CSC Lab
  weight: 2
  params:
    description: 致力于模型预测控制及领域应用的前沿实验室
    address_format: zh-CN
    footer:
      copyright:
        notice: '© {year} 上海交通大学复杂系统智能控制实验室. 保留所有权利.'

fr:
  languageCode: fr-fr
  languageName: Français
  contentDir: content/fr
  title: SJTU CSC Lab
  weight: 3
  params:
    description: Un laboratoire de recherche dédié à l’avancement du contrôle prédictif.
    address_format: fr-FR
    footer:
      copyright:
        notice: '© {year} SJTU CSC Lab. Tous droits réservés.'