# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  title: Complicated System and Control
  weight: 1

zh:
  languageCode: zh-cn
  languageName: 简体中文
  contentDir: content/zh
  title: 复杂系统与控制
  weight: 2
