# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  title: Complex Systems and Control Laboratory
  weight: 1
  params:
    description: A premier research facility dedicated to advancing the field of model predictive control.
    address_format: en-us
    footer:
      copyright:
        notice: '© {year} CSC Lab. All Rights Reserved.'

zh:
  languageCode: zh-cn
  languageName: 简体中文
  contentDir: content/zh
  title: 复杂系统与控制实验室
  weight: 2
  params:
    description: 致力于模型预测控制领域研究的前沿实验室
    address_format: zh-cn
    footer:
      copyright:
        notice: '© {year} 复杂系统与控制实验室. 保留所有权利.'
