# Navigation Links
main:
  - name: Home
    url: /
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Research
    url: project
    weight: 40
  - name: Projects
    url: projects
    weight: 45
  - name: Publications
    url: publication
    weight: 50
  - name: Gallery
    url: gallery
    weight: 60
  - name: Contact
    url: contact
    weight: 70 
