# 导航链接
main:
  - name: 首页
    url: /zh/tour/
    weight: 10
  - name: 新闻
    url: /zh/post/
    weight: 20
  - name: 团队
    url: /zh/people/
    weight: 30
  - name: 项目
    url: /zh/project/
    weight: 40
  - name: 论文
    url: /zh/publication/
    weight: 50
  - name: 联系
    url: /zh/contact/
    weight: 60 