# Navigation Links
main:
  - name: Tour
    url: en/tour
    weight: 10
  - name: News
    url: en/post
    weight: 20
  - name: People
    url: en/people
    weight: 30
  - name: Projects
    url: en/project
    weight: 40
  - name: Publications
    url: en/publication
    weight: 50
  - name: Contact
    url: en/contact
    weight: 60 