backend:
  name: git-gateway
  branch: main

# 多语言配置
i18n:
  # 使用文件夹结构
  structure: multiple_files
  locales: [en, zh]
  default_locale: en

# 媒体文件配置
media_folder: 'static/media'
public_folder: '/media'

collections:
  - name: posts
    label: Posts
    folder: 'content/post'
    create: true
    i18n: true
    fields:
    
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Body, name: body, widget: markdown, i18n: duplicate}

  - name: authors
    label: Authors
    folder: 'content/author'
    create: true
    i18n: true
    fields:
      - {label: Name, name: name, widget: string, i18n: true}
      - {label: Email, name: email, widget: string, i18n: true}
      - {label: Avatar, name: avatar, widget: image, i18n: true}
      - {label: Bio, name: bio, widget: markdown, i18n: duplicate}
      - {label: Website, name: website, widget: string, i18n: true}
      - {label: Location, name: location, widget: string, i18n: true}
      - {label: Social, name: social, widget: list, i18n: true}
      - {label: Posts, name: posts, widget: relation, collection: posts, i18n: true}
      

  - name: projects
    label: Projects
    folder: 'content/project'
    create: true
    i18n: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Body, name: body, widget: markdown, i18n: duplicate}

  # 其他集合... 