backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

local_backend: true

media_folder: 'static/media'
public_folder: '/media'

i18n:
  structure: multiple_folders
  locales: [en, zh]
  default_locale: en

# These are optional configurations
locale: en
display_url: https://csc-lab.netlify.app
site_url: https://csc-lab.netlify.app

collections:
  - name: authors
    label: Authors
    label_singular: Author
    folder: 'content/{{i18n.locale}}/authors'
    path: '{{slug}}/_index'
    filter: {field: "cms_exclude", value: true, negate: true}
    create: true
    i18n: true
    fields:
      - {label: "Display name", name: "title", widget: "string", i18n: true}
      - {label: "Role/position", name: "role", widget: "string", i18n: true}
      - label: "Organizations"
        name: "organizations"
        required: false
        widget: list
        i18n: true
        fields:
          - {label: Name, name: name, widget: string, required: true}
          - {label: URL, name: url, widget: string, required: false}
      - {label: "Bio", name: "bio", widget: "string", required: false, i18n: true}
      - {label: "Interests", name: "interests", required: false, widget: "list", i18n: true}
      - {label: "User Groups", name: "user_groups", type: "list", i18n: true}

  - name: posts
    label: Posts
    label_singular: Post
    folder: 'content/{{i18n.locale}}/post'
    path: '{{slug}}/index'
    create: true
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}

  - name: projects
    label: Projects
    label_singular: Project
    folder: 'content/{{i18n.locale}}/project'
    path: '{{slug}}/index'
    create: true
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Summary", name: "summary", widget: "text", i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "list", i18n: true}
      - {label: "External Link", name: "external_link", widget: "string", required: false}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - {label: "Caption", name: "caption", widget: "string", i18n: true}
          - {label: "Focal Point", name: "focal_point", widget: "string", default: "Smart"}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}

  - name: publications
    label: Publications
    label_singular: Publication
    folder: 'content/{{i18n.locale}}/publication'
    path: '{{slug}}/index'
    create: true
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Authors", name: "authors", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "DOI", name: "doi", widget: "string", required: false}
      - label: "Publication Type"
        name: "publication_types"
        widget: "select"
        multiple: true
        options:
          - {label: "Conference Paper", value: "1"}
          - {label: "Journal Article", value: "2"}
          - {label: "Preprint", value: "3"}
          - {label: "Report", value: "4"}
          - {label: "Book", value: "5"}
          - {label: "Book Section", value: "6"}
          - {label: "Thesis", value: "7"}
          - {label: "Patent", value: "8"}
      - {label: "Publication", name: "publication", widget: "string", i18n: true}
      - {label: "Abstract", name: "abstract", widget: "text", i18n: true}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "list", i18n: true}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}

  - name: pages
    label: Pages
    label_singular: Page
    folder: 'content/{{i18n.locale}}'
    path: '{{slug}}/_index'
    create: true
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Type", name: "type", widget: "string", default: "landing"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Hero"
            name: "block"
            widget: "object"
            fields:
              - {label: "Block Type", name: "block", widget: "hidden", default: "hero"}
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string", i18n: true}
                  - {label: "Text", name: "text", widget: "markdown", i18n: true}
                  - label: "Image"
                    name: "image"
                    widget: "object"
                    fields:
                      - {label: "Filename", name: "filename", widget: "string"}
              - label: "Design"
                name: "design"
                widget: "object"
                fields:
                  - label: "Background"
                    name: "background"
                    widget: "object"
                    fields:
                      - {label: "Gradient End", name: "gradient_end", widget: "string"}
                      - {label: "Gradient Start", name: "gradient_start", widget: "string"}
                      - {label: "Text Color Light", name: "text_color_light", widget: "boolean"}

          - label: "Collection"
            name: "block"
            widget: "object"
            fields:
              - {label: "Block Type", name: "block", widget: "hidden", default: "collection"}
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string", i18n: true}
                  - {label: "Subtitle", name: "subtitle", widget: "string", i18n: true, required: false}
                  - {label: "Text", name: "text", widget: "markdown", i18n: true, required: false}
                  - {label: "Count", name: "count", widget: "number", default: 5}
                  - label: "Filters"
                    name: "filters"
                    widget: "object"
                    fields:
                      - {label: "Folders", name: "folders", widget: "list"}
                      - {label: "Tag", name: "tag", widget: "string", required: false}
                      - {label: "Category", name: "category", widget: "string", required: false}
                      - {label: "Publication Type", name: "publication_type", widget: "string", required: false}
                      - {label: "Featured Only", name: "featured_only", widget: "boolean", default: false}
              - label: "Design"
                name: "design"
                widget: "object"
                fields:
                  - {label: "View", name: "view", widget: "select", options: ["list", "card", "masonry", "showcase"]}
                  - {label: "Columns", name: "columns", widget: "string", default: "2"}

          - label: "Contact"
            name: "block"
            widget: "object"
            fields:
              - {label: "Block Type", name: "block", widget: "hidden", default: "contact"}
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string", i18n: true}
                  - {label: "Text", name: "text", widget: "markdown", i18n: true}
                  - {label: "Email", name: "email", widget: "string"}
                  - {label: "Phone", name: "phone", widget: "string"}
                  - label: "Address"
                    name: "address"
                    widget: "object"
                    fields:
                      - {label: "Street", name: "street", widget: "string"}
                      - {label: "City", name: "city", widget: "string"}
                      - {label: "Region", name: "region", widget: "string"}
                      - {label: "Postcode", name: "postcode", widget: "string"}
                      - {label: "Country", name: "country", widget: "string"}
                      - {label: "Country Code", name: "country_code", widget: "string"}

          - label: "People"
            name: "block"
            widget: "object"
            fields:
              - {label: "Block Type", name: "block", widget: "hidden", default: "people"}
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string", i18n: true}
                  - label: "User Groups"
                    name: "user_groups"
                    widget: "list"
                    i18n: true
                  - {label: "Sort By", name: "sort_by", widget: "string", default: "Params.last_name"}
                  - {label: "Sort Ascending", name: "sort_ascending", widget: "boolean", default: true}
              - label: "Design"
                name: "design"
                widget: "object"
                fields:
                  - {label: "Show Interests", name: "show_interests", widget: "boolean", default: false}
                  - {label: "Show Role", name: "show_role", widget: "boolean", default: true}
                  - {label: "Show Social", name: "show_social", widget: "boolean", default: true}

          - label: "Portfolio"
            name: "block"
            widget: "object"
            fields:
              - {label: "Block Type", name: "block", widget: "hidden", default: "portfolio"}
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string", i18n: true}
                  - {label: "Subtitle", name: "subtitle", widget: "string", i18n: true, required: false}
                  - {label: "Text", name: "text", widget: "markdown", i18n: true, required: false}
                  - label: "Filters"
                    name: "filters"
                    widget: "object"
                    fields:
                      - {label: "Folders", name: "folders", widget: "list"}
                  - {label: "Default Button Index", name: "default_button_index", widget: "number", default: 0}
                  - label: "Buttons"
                    name: "buttons"
                    widget: "list"
                    fields:
                      - {label: "Name", name: "name", widget: "string", i18n: true}
                      - {label: "Tag", name: "tag", widget: "string"}
              - label: "Design"
                name: "design"
                widget: "object"
                fields:
                  - {label: "Columns", name: "columns", widget: "string", default: "1"}
                  - {label: "View", name: "view", widget: "string", default: "showcase"}
                  - {label: "Flip Alt Rows", name: "flip_alt_rows", widget: "boolean", default: false}

          - label: "Slider"
            name: "block"
            widget: "object"
            fields:
              - {label: "Block Type", name: "block", widget: "hidden", default: "slider"}
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - label: "Slides"
                    name: "slides"
                    widget: "list"
                    fields:
                      - {label: "Title", name: "title", widget: "string", i18n: true}
                      - {label: "Content", name: "content", widget: "text", i18n: true}
                      - {label: "Align", name: "align", widget: "select", options: ["left", "center", "right"]}
                      - label: "Background"
                        name: "background"
                        widget: "object"
                        fields:
                          - label: "Image"
                            name: "image"
                            widget: "object"
                            fields:
                              - {label: "Filename", name: "filename", widget: "string"}
                              - label: "Filters"
                                name: "filters"
                                widget: "object"
                                fields:
                                  - {label: "Brightness", name: "brightness", widget: "number", default: 0.7}
                          - {label: "Position", name: "position", widget: "string"}
                          - {label: "Color", name: "color", widget: "string"}
              - label: "Design"
                name: "design"
                widget: "object"
                fields:
                  - {label: "Slide Height", name: "slide_height", widget: "string", required: false}
                  - {label: "Is Fullscreen", name: "is_fullscreen", widget: "boolean", default: true}
                  - {label: "Loop", name: "loop", widget: "boolean", default: false}
                  - {label: "Interval", name: "interval", widget: "number", default: 2000}

  - name: navigation
    label: Navigation
    files:
      - name: en
        label: English Menu
        file: 'config/_default/menus.en.yaml'
        i18n: true
        fields:
          - label: Main Menu
            name: main
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: Weight, name: weight, widget: number}
      
      - name: zh
        label: Chinese Menu
        file: 'config/_default/menus.zh.yaml'
        i18n: true
        fields:
          - label: Main Menu
            name: main
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: Weight, name: weight, widget: number}

  - name: settings
    label: Settings
    files:
      - name: languages
        label: Languages
        file: 'config/_default/languages.yaml'
        fields:
          - label: English
            name: en
            widget: object
            fields:
              - {label: Language Code, name: languageCode, widget: string}
              - {label: Language Name, name: languageName, widget: string}
              - {label: Content Directory, name: contentDir, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Weight, name: weight, widget: number}
          - label: Chinese
            name: zh
            widget: object
            fields:
              - {label: Language Code, name: languageCode, widget: string}
              - {label: Language Name, name: languageName, widget: string}
              - {label: Content Directory, name: contentDir, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Weight, name: weight, widget: number}

      - name: params
        label: Parameters
        file: 'config/_default/params.yaml'
        fields:
          - label: Appearance
            name: appearance
            widget: object
            fields:
              - label: Theme
                name: theme
                widget: select
                options:
                  - { label: "System", value: "system" }
                  - { label: "Light", value: "light" }
                  - { label: "Dark", value: "dark" }
              - label: Font
                name: font
                widget: select
                options:
                  - { label: "Minimal", value: "minimal" }
                  - { label: "Classic", value: "classic" }
                  - { label: "Rose", value: "rose" }
              - label: Font Size
                name: font_size
                widget: select
                options:
                  - { label: "Small", value: "s" }
                  - { label: "Medium", value: "m" }
                  - { label: "Large", value: "l" }
                  - { label: "Extra Large", value: "xl" }

      - name: hugo
        label: Hugo Settings
        file: 'config/_default/hugo.yaml'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Base URL, name: baseURL, widget: string}
          - label: Language Settings
            name: language
            widget: object
            fields:
              - {label: Default Content Language, name: defaultContentLanguage, widget: string}
              - {label: Has CJK Language, name: hasCJKLanguage, widget: boolean}
              - {label: Default Content Language in Subdir, name: defaultContentLanguageInSubdir, widget: boolean}
              - {label: Remove Path Accents, name: removePathAccents, widget: boolean}

  - name: i18n
    label: Translations
    files:
      - name: zh
        label: Chinese Translations
        file: 'i18n/zh.yaml'
        fields:
          - label: Navigation
            name: navigation
            widget: list
            fields:
              - {label: ID, name: id, widget: string}
              - {label: Translation, name: translation, widget: string}
          - label: General
            name: general
            widget: list
            fields:
              - {label: ID, name: id, widget: string}
              - {label: Translation, name: translation, widget: string}
          - label: Buttons
            name: buttons
            widget: list
            fields:
              - {label: ID, name: id, widget: string}
              - {label: Translation, name: translation, widget: string}
          - label: Publications
            name: publications
            widget: list
            fields:
              - {label: ID, name: id, widget: string}
              - {label: Translation, name: translation, widget: string}

  - name: media
    label: Media Library
    folder: 'static/media'
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Alt Text, name: alt, widget: string, i18n: true}
      - {label: Caption, name: caption, widget: string, i18n: true, required: false} 