backend:
  name: git-gateway
  branch: main

# 多语言配置
i18n:
  # 使用文件夹结构
  structure: multiple_folders
  locales: [en, zh]
  default_locale: en

# 媒体文件配置
media_folder: 'static/media'
public_folder: '/media'

collections:
  - name: posts
    label: Posts
    folder: 'content/{{locale}}/post'
    create: true
    i18n: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Body, name: body, widget: markdown, i18n: duplicate}

  - name: projects
    label: Projects
    folder: 'content/{{locale}}/project'
    create: true
    i18n: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Body, name: body, widget: markdown, i18n: duplicate}

  # 其他集合... 